apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgAKA2Hrco8GunlavCLA8f56D9KA0Ev1slxF0eNoL34RXGvfmDFpjfBRL13Od73P4Buvjswadn+bgJwOba3x6x6msGOU9RMdG/f5f+wcB28qQzOAguixHAruYgeMVcMr0ScWYUE9A1yKGTEO+C3+wV44n136+d1p6GX4v4BMmMlUtqrAJdzfKZD97aiQk4uaX8Nzx5FpvN4PyaRB4W5WZr3sgk2b7xPYswmjaOGSbebgkaA+u6/hP+cJ2e/UNw+eFX7qi/iPIWaSIz/nAmBYwsLr+HpCaLbof4EcZlj+Pz5UmAzUhIrCkwzPqskIeOlm9Sj2PeYq6zrPwO0iAXuC+hePixJwZ7g0yuR+zgfdnZC1xmwwZDTYKh6ooyfKWmgon4TwrcVfOKvY/IPXiG8nlt/jIVnTPaP9Cs+3mTdpOluhOoLKRR50Hrj+Eqg/incf7Glb3mkesstaf3oFJ4X9a8puwuKEV1CAp+sc/NbMhk1lm8gXuYdJhaVEJynNGZuyVZ2K2izl+yJjzD1h06hWSZX65t0ADQYnFQnMHwzagJXFHGaN09W4vH29ijxWMdrmCCuDnhR/en7Iyjv16Qi5//7BM8NcVgJxAzA7vrCr84gZqXmHRMw2xysOPvVxaltC/hX+SmzwYuW4WhSedNKDtV/8qdxOjv4bUSB1HA+1vMyXWOTFc/ssFN65/qNl2AerZotrdznFSinYDjCKvqD7wq5Pcr8+gbtvNhzvYUxc7zSyQH/MQXAdNCP1radhccmxPX/024mbAWMOzC7pw5A06cnuCc0mBW9DJo2psKxHdU/X9+PMGY3LXFd+IrflLMRMCfkJ1FeHpFmJIZlC8/vo/dG5TTDBTNwIMAhnA3lR2CP6u9/NN3PskNj+d89IIlcXFObPhhp1uzQBtqUpIpgs3Aci8I0roZ+1Jah4Bj5pkk4GLLR8rhINY0ZqWbi0qKZTGxm4PK0aNTW8YfHiguhC0QPUi/AQHhaE2UP05FNxeD1lwhKJJyQPiKFW6DOx0pRfrb3g/MyCpN1K0RbVrSnu2CzJn/8c4AQLsbMn22P7501xnQGDvGAO0fe4jpcb8TUY0mEzjOfS2IZdKY6ZA8EsKtKYUWqYba+K5umObFR4QQt0oq/Fs1EvX3B3hljIv6oHy9wXESjguK2LZdj8syTIsjuvfF4d++DWemv9Tyrd9iQNwHmnG8FYy2H66U6hWemXqnx6g38NFNPvg6iG6Bo79wR8MdcdKXky2O6Mo5VQA42JHD4WzNjyGHyxm9uV+h8XXMnvDp+dY2PowqbyRggh3hg5LzVGOEEnJvajiwaMqIensu1+vXqG0ofUFmc/EPnoteybxEwQUlHhZd0cINwzzZdS1MEScuaJFu5Corr6hyD9l3dSS6gM
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson

